"""Fan 制御（Supervisor + Learned MPC + Reactive Guard + Critical Safety）。

構成は決定記録 0027、層間の契約は決定記録 0028。

**LLM はここへ到達できない。** `ai/` は `control/` を import しない（AGENTS.md ルール1）。
Fan Demand を変えられるのは、定義済みの Control Pipeline を通った値だけ（AGENTS.md ルール2）。
"""

from coldaisle.control.acoustic import (
    ACOUSTIC_CONFIG_FILENAME,
    ACOUSTIC_CONFIG_VERSION,
    AcousticCostEstimate,
    AcousticCostMetadata,
    AcousticCostModel,
    AcousticInteraction,
    AcousticModelConfig,
    AcousticModelSource,
    ConfiguredAcousticCostModel,
    DisabledAcousticCostModel,
    ZoneAcousticCurve,
    load_acoustic_model,
)
from coldaisle.control.air_balance import (
    AIR_BALANCE_CONFIG_FILENAME,
    AIR_BALANCE_CONFIG_VERSION,
    AirBalanceConfig,
    AirBalanceCoordination,
    AirBalanceEstimate,
    AirBalanceMetadata,
    AirBalanceModel,
    AirBalanceState,
    BalanceBand,
    CharacterizationSource,
    ConfiguredAirBalanceModel,
    FlowCurvePoint,
    ThermalInputs,
    ThermalLimits,
    ZoneFlowCurve,
    ZoneFlowEstimate,
    load_air_balance_model,
)
from coldaisle.control.config import (
    CONFIG_FILENAMES,
    CONTROL_CONFIG_VERSION,
    ControlConfig,
    ProvisionalConfigValue,
)
from coldaisle.control.hardware import (
    FanHardwareBackend,
    FanHardwareResult,
    SimulatedFanBackend,
    SimulatedFaultPlan,
)
from coldaisle.control.logging import ControlTraceLogger, ControlTraceSink
from coldaisle.control.schema import (
    BOUND_BY_PRECEDENCE,
    EMERGENCY_FAULTS,
    SCHEMA_VERSION,
    TOP_EMERGENCY_FAULTS,
    ZONE_FAULTS,
    AuthorityStage,
    BoundBy,
    ControllerKind,
    ControllerProposal,
    ControlState,
    ControlTick,
    Demand,
    EffectiveZoneDemand,
    Fault,
    FaultCode,
    GuardZoneOutput,
    HardwareReadback,
    OperatingMode,
    OptimizerStatus,
    PerZone,
    Reason,
    SafetyState,
    SafetyZoneOutput,
    Zone,
    ZoneRecord,
    ZoneRequest,
)

__all__ = [
    "ACOUSTIC_CONFIG_FILENAME",
    "ACOUSTIC_CONFIG_VERSION",
    "AIR_BALANCE_CONFIG_FILENAME",
    "AIR_BALANCE_CONFIG_VERSION",
    "BOUND_BY_PRECEDENCE",
    "CONFIG_FILENAMES",
    "CONTROL_CONFIG_VERSION",
    "EMERGENCY_FAULTS",
    "SCHEMA_VERSION",
    "TOP_EMERGENCY_FAULTS",
    "ZONE_FAULTS",
    "AcousticCostEstimate",
    "AcousticCostMetadata",
    "AcousticCostModel",
    "AcousticInteraction",
    "AcousticModelConfig",
    "AcousticModelSource",
    "AirBalanceConfig",
    "AirBalanceCoordination",
    "AirBalanceEstimate",
    "AirBalanceMetadata",
    "AirBalanceModel",
    "AirBalanceState",
    "AuthorityStage",
    "BalanceBand",
    "BoundBy",
    "CharacterizationSource",
    "ConfiguredAcousticCostModel",
    "ConfiguredAirBalanceModel",
    "ControlConfig",
    "ControlState",
    "ControlTick",
    "ControlTraceLogger",
    "ControlTraceSink",
    "ControllerKind",
    "ControllerProposal",
    "Demand",
    "DisabledAcousticCostModel",
    "EffectiveZoneDemand",
    "FanHardwareBackend",
    "FanHardwareResult",
    "Fault",
    "FaultCode",
    "FlowCurvePoint",
    "GuardZoneOutput",
    "HardwareReadback",
    "OperatingMode",
    "OptimizerStatus",
    "PerZone",
    "ProvisionalConfigValue",
    "Reason",
    "SafetyState",
    "SafetyZoneOutput",
    "SimulatedFanBackend",
    "SimulatedFaultPlan",
    "ThermalInputs",
    "ThermalLimits",
    "Zone",
    "ZoneAcousticCurve",
    "ZoneFlowCurve",
    "ZoneFlowEstimate",
    "ZoneRecord",
    "ZoneRequest",
    "load_acoustic_model",
    "load_air_balance_model",
]
