"""Fan 制御（Supervisor + Learned MPC + Reactive Guard + Critical Safety）。

構成は決定記録 0027、層間の契約は決定記録 0028。

**LLM はここへ到達できない。** `ai/` は `control/` を import しない（AGENTS.md ルール1）。
Fan Demand を変えられるのは、定義済みの Control Pipeline を通った値だけ（AGENTS.md ルール2）。
"""

from coldaisle.control.acoustic import (
    ACOUSTIC_CONFIG_FILENAME,
    ACOUSTIC_CONFIG_VERSION,
    AcousticCostEstimate,
    AcousticCostMetadata,
    AcousticCostModel,
    AcousticInteraction,
    AcousticModelConfig,
    AcousticModelSource,
    ConfiguredAcousticCostModel,
    DisabledAcousticCostModel,
    ZoneAcousticCurve,
    load_acoustic_model,
)
from coldaisle.control.config import (
    CONFIG_FILENAMES,
    CONTROL_CONFIG_VERSION,
    SAFETY_CONFIG_VERSION,
    ControlConfig,
    ProvisionalConfigValue,
)
from coldaisle.control.hardware import (
    FanHardwareBackend,
    FanHardwareResult,
    SimulatedFanBackend,
    SimulatedFaultPlan,
)
from coldaisle.control.logging import ControlTraceLogger, ControlTraceSink
from coldaisle.control.safety import (
    ABSOLUTE_TEMPERATURE_METRICS,
    AIR_TELEMETRY_GROUP,
    AIR_TEMPERATURE_METRICS,
    CPU_TEMPERATURE_METRIC,
    GPU_TEMPERATURE_METRIC,
    ComposedDemands,
    ControlRuntimeBinding,
    CriticalSafety,
    CriticalSafetyDecision,
    DemandComposer,
    EmergencyControlRuntime,
    HandoffRecordError,
    HandoffResult,
    HandoffZoneResult,
    create_control_runtime_binding,
    create_emergency_control_runtime,
    emergency_handoff,
    invalid_config_decision,
)
from coldaisle.control.schema import (
    BOUND_BY_PRECEDENCE,
    EMERGENCY_FAULTS,
    SCHEMA_VERSION,
    TOP_EMERGENCY_FAULTS,
    ZONE_FAULTS,
    AuthorityStage,
    BoundBy,
    ControllerKind,
    ControllerProposal,
    ControlState,
    ControlTick,
    Demand,
    EffectiveZoneDemand,
    Fault,
    FaultCode,
    GuardZoneOutput,
    HardwareReadback,
    OperatingMode,
    OptimizerStatus,
    PerZone,
    Reason,
    SafetyState,
    SafetyZoneOutput,
    Zone,
    ZoneRecord,
    ZoneRequest,
)

__all__ = [
    "ABSOLUTE_TEMPERATURE_METRICS",
    "ACOUSTIC_CONFIG_FILENAME",
    "ACOUSTIC_CONFIG_VERSION",
    "AIR_TELEMETRY_GROUP",
    "AIR_TEMPERATURE_METRICS",
    "BOUND_BY_PRECEDENCE",
    "CONFIG_FILENAMES",
    "CONTROL_CONFIG_VERSION",
    "CPU_TEMPERATURE_METRIC",
    "EMERGENCY_FAULTS",
    "GPU_TEMPERATURE_METRIC",
    "SAFETY_CONFIG_VERSION",
    "SCHEMA_VERSION",
    "TOP_EMERGENCY_FAULTS",
    "ZONE_FAULTS",
    "AcousticCostEstimate",
    "AcousticCostMetadata",
    "AcousticCostModel",
    "AcousticInteraction",
    "AcousticModelConfig",
    "AcousticModelSource",
    "AuthorityStage",
    "BoundBy",
    "ComposedDemands",
    "ConfiguredAcousticCostModel",
    "ControlConfig",
    "ControlRuntimeBinding",
    "ControlState",
    "ControlTick",
    "ControlTraceLogger",
    "ControlTraceSink",
    "ControllerKind",
    "ControllerProposal",
    "CriticalSafety",
    "CriticalSafetyDecision",
    "Demand",
    "DemandComposer",
    "DisabledAcousticCostModel",
    "EffectiveZoneDemand",
    "EmergencyControlRuntime",
    "FanHardwareBackend",
    "FanHardwareResult",
    "Fault",
    "FaultCode",
    "GuardZoneOutput",
    "HandoffRecordError",
    "HandoffResult",
    "HandoffZoneResult",
    "HardwareReadback",
    "OperatingMode",
    "OptimizerStatus",
    "PerZone",
    "ProvisionalConfigValue",
    "Reason",
    "SafetyState",
    "SafetyZoneOutput",
    "SimulatedFanBackend",
    "SimulatedFaultPlan",
    "Zone",
    "ZoneAcousticCurve",
    "ZoneRecord",
    "ZoneRequest",
    "create_control_runtime_binding",
    "create_emergency_control_runtime",
    "emergency_handoff",
    "invalid_config_decision",
    "load_acoustic_model",
]
